import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { parseScenarios, toKebabCase } from './scenario-parser.js';

// ============================================================================
// FIXTURE SPEC
// ============================================================================

const AUTH_SPEC = `# Auth Specification

> Generated by openlore v1.0.0 on 2025-06-15

## Requirements

### Requirement: UserLogin

The system SHALL authenticate users.

#### Scenario: SuccessfulLogin
- **GIVEN** a registered user with email "alice@test.com" and a valid password
- **WHEN** POST /api/auth/login is called with those credentials
- **THEN** the system returns a JWT token, expiry time, and userId with status 200

#### Scenario: InvalidCredentials
- **GIVEN** an incorrect password
- **WHEN** POST /api/auth/login is called
- **THEN** the system returns status 401 with error "Invalid credentials"

#### Scenario: IncompleteNoThen
- **GIVEN** something
- **WHEN** something happens

### Requirement: UserRegistration

The system SHALL register users.

#### Scenario: SuccessfulRegistration
- **GIVEN** a unique email "bob@test.com"
- **WHEN** POST /api/auth/register is called
- **THEN** the system creates the user and returns a JWT with status 201
`;

const TASKS_SPEC = `# Tasks Specification

## Requirements

### Requirement: TaskCreation

#### Scenario: ValidCreation
- **GIVEN** a valid title and projectId
- **WHEN** POST /api/tasks is called
- **THEN** the system creates the task with default status "todo" and returns it with status 201
`;

// ============================================================================
// HELPERS
// ============================================================================

async function createFixture(
  dir: string,
  specs: Record<string, string>
): Promise<void> {
  for (const [domain, content] of Object.entries(specs)) {
    const specDir = join(dir, 'openspec', 'specs', domain);
    await mkdir(specDir, { recursive: true });
    await writeFile(join(specDir, 'spec.md'), content);
  }
}

// ============================================================================
// TESTS
// ============================================================================

describe('parseScenarios', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = join(tmpdir(), `openlore-test-${Date.now()}`);
    await mkdir(tmpDir, { recursive: true });
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  it('returns empty array when no specs exist', async () => {
    const result = await parseScenarios({ rootPath: tmpDir });
    expect(result).toEqual([]);
  });

  it('parses all complete scenarios from a spec file', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });

    // IncompleteNoThen should be skipped
    expect(result).toHaveLength(3);
  });

  it('extracts correct G/W/T for a scenario', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });
    const login = result.find((s) => s.scenarioName === 'SuccessfulLogin');

    expect(login).toBeDefined();
    expect(login!.domain).toBe('auth');
    expect(login!.requirement).toBe('UserLogin');
    expect(login!.given).toEqual([
      'a registered user with email "alice@test.com" and a valid password',
    ]);
    expect(login!.when).toEqual([
      'POST /api/auth/login is called with those credentials',
    ]);
    expect(login!.then).toEqual([
      'the system returns a JWT token, expiry time, and userId with status 200',
    ]);
  });

  it('filters by domain', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC, tasks: TASKS_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir, domains: ['auth'] });

    expect(result.every((s) => s.domain === 'auth')).toBe(true);
    expect(result.some((s) => s.domain === 'tasks')).toBe(false);
  });

  it('respects limit', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC, tasks: TASKS_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir, limit: 2 });
    expect(result).toHaveLength(2);
  });

  it('parses scenarios from multiple domains', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC, tasks: TASKS_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });
    const domains = new Set(result.map((s) => s.domain));
    expect(domains.has('auth')).toBe(true);
    expect(domains.has('tasks')).toBe(true);
  });

  it('sets default annotation fields (skip=false, tags=[], priority=normal)', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });
    for (const s of result) {
      expect(s.skip).toBe(false);
      expect(s.tags).toEqual([]);
      expect(s.priority).toBe('normal');
    }
  });

  it('excludes domains via excludeDomains', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC, tasks: TASKS_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir, excludeDomains: ['auth'] });
    expect(result.every((s) => s.domain === 'tasks')).toBe(true);
  });

  it('parses skip annotation', async () => {
    const ANNOTATED_SPEC = `# Test Spec\n\n## Requirements\n\n### Requirement: Req\n\n#### Scenario: Skipped\n<!-- openlore-test: skip reason="deprecated" -->\n- **GIVEN** something\n- **WHEN** something\n- **THEN** something\n\n#### Scenario: Active\n- **GIVEN** something\n- **WHEN** something\n- **THEN** something\n`;
    await createFixture(tmpDir, { demo: ANNOTATED_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });
    expect(result.map((s) => s.scenarioName)).toEqual(['Active']);
  });

  it('includes skipped scenarios when includeSkipped=true', async () => {
    const ANNOTATED_SPEC = `# Test Spec\n\n## Requirements\n\n### Requirement: Req\n\n#### Scenario: Skipped\n<!-- openlore-test: skip reason="deprecated" -->\n- **GIVEN** something\n- **WHEN** something\n- **THEN** something\n`;
    await createFixture(tmpDir, { demo: ANNOTATED_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir, includeSkipped: true });
    expect(result).toHaveLength(1);
    expect(result[0].skip).toBe(true);
    expect(result[0].skipReason).toBe('deprecated');
  });

  it('parses priority and tags annotations', async () => {
    const ANNOTATED_SPEC = `# Test Spec\n\n## Requirements\n\n### Requirement: Req\n\n#### Scenario: HighPrio\n<!-- openlore-test: priority=high tags=smoke,regression -->\n- **GIVEN** something\n- **WHEN** something\n- **THEN** something\n`;
    await createFixture(tmpDir, { demo: ANNOTATED_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });
    expect(result[0].priority).toBe('high');
    expect(result[0].tags).toEqual(['smoke', 'regression']);
  });

  it('filters by tags', async () => {
    const ANNOTATED_SPEC = `# Test Spec\n\n## Requirements\n\n### Requirement: Req\n\n#### Scenario: Tagged\n<!-- openlore-test: tags=smoke -->\n- **GIVEN** something\n- **WHEN** something\n- **THEN** something\n\n#### Scenario: Untagged\n- **GIVEN** something\n- **WHEN** something\n- **THEN** something\n`;
    await createFixture(tmpDir, { demo: ANNOTATED_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir, tags: ['smoke'] });
    expect(result).toHaveLength(1);
    expect(result[0].scenarioName).toBe('Tagged');
  });

  it('sets empty mappedFunctions when no mapping.json', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC });

    const result = await parseScenarios({ rootPath: tmpDir });
    expect(result.every((s) => s.mappedFunctions.length === 0)).toBe(true);
  });

  it('enriches with mappedFunctions from mapping.json', async () => {
    await createFixture(tmpDir, { auth: AUTH_SPEC });

    const analysisDir = join(tmpDir, '.openlore', 'analysis');
    await mkdir(analysisDir, { recursive: true });
    const mapping = {
      generatedAt: new Date().toISOString(),
      mappings: [
        {
          requirement: 'UserLogin',
          domain: 'auth',
          specFile: 'openspec/specs/auth/spec.md',
          functions: [
            { name: 'login', file: 'src/auth/auth-service.ts', line: 42, confidence: 'llm' },
          ],
        },
      ],
    };
    await writeFile(join(analysisDir, 'mapping.json'), JSON.stringify(mapping));

    const result = await parseScenarios({ rootPath: tmpDir });
    const loginScenario = result.find((s) => s.requirement === 'UserLogin');
    expect(loginScenario!.mappedFunctions).toHaveLength(1);
    expect(loginScenario!.mappedFunctions[0].name).toBe('login');
    expect(loginScenario!.mappedFunctions[0].confidence).toBe('llm');
  });
});

describe('toKebabCase', () => {
  it('converts PascalCase to kebab-case', () => {
    expect(toKebabCase('UserLogin')).toBe('user-login');
    expect(toKebabCase('TaskCreation')).toBe('task-creation');
  });

  it('handles already-lowercase words', () => {
    expect(toKebabCase('login')).toBe('login');
  });

  it('strips special characters', () => {
    expect(toKebabCase('User Login!')).toBe('user-login');
  });
});
