/**
 * Viewer themes — each theme is a map of CSS custom properties.
 *
 * The root <div> of InteractiveGraphViewer applies `theme.vars` as inline style,
 * making all CSS variables available to every descendant via `var(--xxx)`.
 */

export const THEMES = {
  space: {
    label: '⬡ space',
    vars: {
      '--bg-base':         '#07091a',
      '--bg-panel':        '#080a1c',
      '--bg-raised':       '#0e1028',
      '--bg-input':        '#0d0f22',
      '--bg-hover':        '#131630',
      '--bg-select':       '#181b38',
      '--bg-deep':         '#080b1e',
      '--bg-node':         '#0b0d1e',
      '--bd-faint':        '#0f1224',
      '--bd-muted':        '#1a1f38',
      '--bd-dim':          '#0e1025',
      '--bd-edge':         '#181c36',
      '--tx-primary':      '#c8cde8',
      '--tx-secondary':    '#8890b0',
      '--tx-bright':       '#e0e4f0',
      '--tx-muted':        '#6a70a0',
      '--tx-dim':          '#3a4060',
      '--tx-faint':        '#2a2f4a',
      '--tx-ghost':        '#3a3f5c',
      '--tx-node':         '#5a6090',
      '--tx-node-sel':     '#ffffff',
      '--ac-primary':      '#7c6af7',
      '--ac-teal':         '#3ecfcf',
      '--ac-edge-type':    '#252a4a',
      '--ac-arrow':        '#1e2340',
      '--ac-cluster-arr':  '#2a3060',
    },
  },

  terminal: {
    label: '▶ terminal',
    vars: {
      '--bg-base':         '#010d01',
      '--bg-panel':        '#020e02',
      '--bg-raised':       '#061206',
      '--bg-input':        '#041004',
      '--bg-hover':        '#0a1a0a',
      '--bg-select':       '#0d200d',
      '--bg-deep':         '#030e03',
      '--bg-node':         '#040f04',
      '--bd-faint':        '#071807',
      '--bd-muted':        '#0f2f0f',
      '--bd-dim':          '#061806',
      '--bd-edge':         '#0d200d',
      '--tx-primary':      '#80ee80',
      '--tx-secondary':    '#50a050',
      '--tx-bright':       '#c0ffc0',
      '--tx-muted':        '#408040',
      '--tx-dim':          '#285028',
      '--tx-faint':        '#1a3a1a',
      '--tx-ghost':        '#204020',
      '--tx-node':         '#40704a',
      '--tx-node-sel':     '#c0ffc0',
      '--ac-primary':      '#4ade80',
      '--ac-teal':         '#00d4aa',
      '--ac-edge-type':    '#103020',
      '--ac-arrow':        '#0d2010',
      '--ac-cluster-arr':  '#143820',
    },
  },

  midnight: {
    label: '◈ midnight',
    vars: {
      '--bg-base':         '#000000',
      '--bg-panel':        '#050505',
      '--bg-raised':       '#0a0a0a',
      '--bg-input':        '#080808',
      '--bg-hover':        '#111111',
      '--bg-select':       '#161616',
      '--bg-deep':         '#060606',
      '--bg-node':         '#090909',
      '--bd-faint':        '#0e0e0e',
      '--bd-muted':        '#1c1c1c',
      '--bd-dim':          '#0c0c0c',
      '--bd-edge':         '#141414',
      '--tx-primary':      '#00d4e8',
      '--tx-secondary':    '#007a88',
      '--tx-bright':       '#80eeff',
      '--tx-muted':        '#005060',
      '--tx-dim':          '#003040',
      '--tx-faint':        '#001a20',
      '--tx-ghost':        '#002530',
      '--tx-node':         '#004558',
      '--tx-node-sel':     '#80eeff',
      '--ac-primary':      '#00e5ff',
      '--ac-teal':         '#00ff88',
      '--ac-edge-type':    '#001828',
      '--ac-arrow':        '#001020',
      '--ac-cluster-arr':  '#001e30',
    },
  },

  warm: {
    label: '☀ warm',
    vars: {
      '--bg-base':         '#1c1711',
      '--bg-panel':        '#221e17',
      '--bg-raised':       '#2a2318',
      '--bg-input':        '#261f14',
      '--bg-hover':        '#302818',
      '--bg-select':       '#38301e',
      '--bg-deep':         '#201b11',
      '--bg-node':         '#201a0e',
      '--bd-faint':        '#2a2218',
      '--bd-muted':        '#3a3020',
      '--bd-dim':          '#281f14',
      '--bd-edge':         '#302810',
      '--tx-primary':      '#d4c59a',
      '--tx-secondary':    '#9a8060',
      '--tx-bright':       '#ede0c0',
      '--tx-muted':        '#806840',
      '--tx-dim':          '#605038',
      '--tx-faint':        '#483820',
      '--tx-ghost':        '#504030',
      '--tx-node':         '#706040',
      '--tx-node-sel':     '#ede0c0',
      '--ac-primary':      '#e8a020',
      '--ac-teal':         '#50b060',
      '--ac-edge-type':    '#382808',
      '--ac-arrow':        '#302408',
      '--ac-cluster-arr':  '#402808',
    },
  },
  light: {
    label: '○ light',
    vars: {
      '--bg-base':         '#f4f5f9',
      '--bg-panel':        '#eef0f6',
      '--bg-raised':       '#ffffff',
      '--bg-input':        '#ffffff',
      '--bg-hover':        '#e8eaf2',
      '--bg-select':       '#dde0ef',
      '--bg-deep':         '#f0f1f8',
      '--bg-node':         '#ffffff',
      '--bd-faint':        '#dde0ec',
      '--bd-muted':        '#c8ccde',
      '--bd-dim':          '#e2e4f0',
      '--bd-edge':         '#c4c8de',
      '--tx-primary':      '#1a1c2e',
      '--tx-secondary':    '#4a4f6e',
      '--tx-bright':       '#0a0c1a',
      '--tx-muted':        '#6a6f90',
      '--tx-dim':          '#9098b8',
      '--tx-faint':        '#b0b6cc',
      '--tx-ghost':        '#c0c6d8',
      '--tx-node':         '#4a5070',
      '--tx-node-sel':     '#ffffff',
      '--ac-primary':      '#5b4de0',
      '--ac-teal':         '#0e9e9e',
      '--ac-edge-type':    '#c8cce8',
      '--ac-arrow':        '#a8aed0',
      '--ac-cluster-arr':  '#9098c0',
    },
  },
};

export const THEME_KEYS = Object.keys(THEMES);
export const DEFAULT_THEME = 'space';
