/**
 * Codebase Digest — generates .openlore/CODEBASE.md
 *
 * A compact, agent-readable Markdown summary of the codebase produced by
 * `openlore analyze`.  Designed to be included in CLAUDE.md / .clinerules
 * so agents absorb architectural context passively at session start, without
 * needing to call any MCP tool.
 *
 * Content:
 *   - Entry points (functions with no internal callers)
 *   - Critical hubs (highest fan-in functions)
 *   - Spec domains (if openspec/specs/ exists)
 *   - Most coupled files (high in-degree in dependency graph)
 *   - God functions / oversized orchestrators
 *   - Layer violations (if any)
 */

import { readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { confinedAtomicWriteFile } from '../../utils/path-confinement.js';
import { frameServedContent } from '../services/served-content.js';
import type { LLMContext, RepoStructure } from './artifact-generator.js';
import { collectExternalWiring } from './entry-point-adapters.js';
import type { DependencyGraphResult } from './dependency-graph.js';
import { languageCoverageMatrix, renderCoverageMatrixMarkdown } from './language-support.js';

// ============================================================================
// TYPES
// ============================================================================

interface DigestOptions {
  /** Absolute path to the project root */
  rootPath: string;
  /** Absolute path to the .openlore/analysis/ output directory */
  outputDir: string;
  /** Max entry points to list */
  maxEntryPoints?: number;
  /** Max hub functions to list */
  maxHubs?: number;
  /** Max god functions to list */
  maxGodFunctions?: number;
  /** Max most-coupled files to list */
  maxCoupledFiles?: number;
  /** Reconciled analyzer-owned domains; never inferred again by this consumer. */
  repoStructure?: RepoStructure;
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Neutralize repo-derived text before it is interpolated into a Markdown row.
 *
 * Every name in this digest comes from the ANALYZED repository — function names, class names,
 * directory-derived domain names, file paths. A name carrying a newline or a `|` could close the
 * row and forge further table rows (or whole sections) in a file that is @-imported into the
 * developer's agent instructions; a backtick could close the code span the value sits in and let
 * the rest render as markup. Structure is stripped, the text itself is not rewritten — the
 * surrounding frame (below) is what says the content is data.
 *
 * STRIPPED, not escaped. Escaping `|` as `\\|` was incomplete: a backslash is not itself
 * escaped, so `a\\|b` became `a\\\\|b` — an escaped BACKSLASH followed by a live pipe, which
 * closes the cell anyway. Removing the structural characters has no such ordering hazard.
 */
function repoText(value: string): string {
  return value.replace(/[\r\n|`]+/g, ' ');
}

function rel(absPath: string, rootPath: string): string {
  return absPath.startsWith(rootPath)
    ? absPath.slice(rootPath.length).replace(/^\//, '')
    : absPath;
}

/** Extract per-file coupling from pre-computed node metrics */
function fileCoupling(depGraph: DependencyGraphResult | null): Array<{ path: string; importedBy: number; imports: number }> {
  if (!depGraph) return [];
  return depGraph.nodes
    .map(n => ({
      path: n.file?.path ?? n.id,
      importedBy: n.metrics?.inDegree ?? 0,
      imports: n.metrics?.outDegree ?? 0,
    }))
    .sort((a, b) => b.importedBy - a.importedBy);
}

// ============================================================================
// MAIN EXPORT
// ============================================================================

/**
 * Generate `.openlore/CODEBASE.md` from cached analysis artifacts.
 *
 * Non-fatal: logs a warning and returns false if generation fails.
 */
export async function generateCodebaseDigest(
  llmContext: LLMContext,
  depGraph: DependencyGraphResult | null,
  opts: DigestOptions,
): Promise<boolean> {
  try {
    const {
      rootPath,
      outputDir,
      maxEntryPoints = 8,
      maxHubs = 10,
      maxGodFunctions = 5,
      maxCoupledFiles = 8,
      repoStructure,
    } = opts;

    const cg = llmContext.callGraph;
    const lines: string[] = [];
    lines.push(`# Codebase — architecture digest`);
    lines.push(`> Generated by openlore analyze. Re-run after significant refactors.`);
    lines.push(`> Add this file to CLAUDE.md or .clinerules so agents absorb it at session start.`);
    lines.push('');
    // Everything from here to the MCP-workflow section is derived from the ANALYZED repository and
    // is @-imported verbatim into the developer's agent instructions. That is the same untrusted
    // channel `orient --inject` serves, so it gets the same treatment: the repo-derived body is
    // wrapped by `frameServedContent` below. OpenLore's own title and workflow guidance stay
    // OUTSIDE the frame — framing them would label our instructions as data.
    const bodyStart = lines.length;

    // ── Overview ──────────────────────────────────────────────────────────────
    if (cg) {
      // Production functions only: cg.nodes also carries test and external (library)
      // nodes so the test-impact tools can use them. The digest describes the
      // production surface, so exclude both — otherwise test helpers and stdlib
      // calls inflate the counts and leak into the god-function list (e.g. a Java
      // `FooTest.checkOption` showing up as an orchestrator).
      const prodNodes = cg.nodes.filter(n => !n.isTest && !n.isExternal);
      // `stats.totalEdges` counts ALL `calls` edges — including test-caller and
      // external-callee edges — so labeling it "internal" next to the production-only
      // function count mixes two populations under one qualifier. Count only edges
      // whose BOTH endpoints are production nodes, matching `prodNodes` above.
      const prodNodeIds = new Set(prodNodes.map(n => n.id));
      const internalEdges = cg.edges.filter(
        e => (!e.kind || e.kind === 'calls') && prodNodeIds.has(e.callerId) && prodNodeIds.has(e.calleeId)
      ).length;
      lines.push('## Overview');
      lines.push(`- **${prodNodes.length}** functions / methods analyzed`);
      lines.push(`- **${internalEdges}** internal call edges`);
      // Decompose entry points into config-wired vs. orphaned (change: add-framework-entry-point-adapters).
      const wired = rootPath
        ? new Set((await collectExternalWiring(rootPath).catch(() => ({ wired: [] }))).wired.map(w => w.file))
        : new Set<string>();
      const wiredEntryPoints = (cg.entryPoints ?? [])
        .filter(n => wired.has(n.filePath.replaceAll('\\', '/').replace(/^\.\//, ''))).length;
      const entryPointCount = cg.entryPoints?.length ?? 0;
      lines.push(`- **${entryPointCount}** entry points (no internal callers)` + (rootPath && entryPointCount > 0
        ? `: **${wiredEntryPoints}** in files a config invokes (package.json, tsconfig, test-runner config, CI run steps), **${entryPointCount - wiredEntryPoints}** invoked by no config read`
        : ''));
      lines.push(`- **${cg.hubFunctions?.length ?? 0}** hub functions (high fan-in)`);
      if (cg.stats?.avgFanIn !== undefined) {
        lines.push(`- avg fan-in: **${cg.stats.avgFanIn.toFixed(2)}**, avg fan-out: **${cg.stats.avgFanOut.toFixed(2)}**`);
      }
      lines.push('');
    }

    // ── Language coverage ─────────────────────────────────────────────────────
    // A deterministic capability matrix over the repo's detected languages, so a
    // quiet structural result is interpretable: "·" means the capability is not
    // backed for that language (fail-soft), not that there were no matches.
    if (cg) {
      const detected = [...new Set(
        cg.nodes.filter(n => !n.isExternal && n.language && n.language !== 'unknown').map(n => n.language),
      )].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
      const detectedSet = new Set(detected);
      const additionallyBacked = languageCoverageMatrix().rows
        .filter(row => row.supportedCount > 0 && !detectedSet.has(row.language))
        .map(row => row.language);
      lines.push('## Language coverage');
      lines.push('This table is scoped to languages detected in this repository (`✓` backed, `·` fail-soft / not claimed). A `·` cell means a quiet result for that capability is "unsupported here", not "nothing found".');
      lines.push('');
      lines.push(...renderCoverageMatrixMarkdown(languageCoverageMatrix(detected)));
      lines.push('');
      if (additionallyBacked.length > 0) {
        lines.push(`Registry additionally backs: ${additionallyBacked.join(', ')}. Query \`get_language_support\` for the full matrix.`);
        lines.push('');
      }
      lines.push('> Query this at runtime with the `get_language_support` MCP tool (opt-in). See the "add a language" checklist in the docs.');
      lines.push('');
    }

    // ── Entry points ──────────────────────────────────────────────────────────
    if (cg?.entryPoints?.length) {
      lines.push('## Entry points');
      lines.push('Functions with no internal callers — the natural starting point for any task.');
      lines.push('');
      lines.push('| Function | File | fanOut |');
      lines.push('|----------|------|--------|');
      for (const ep of cg.entryPoints.slice(0, maxEntryPoints)) {
        const file = rel(ep.filePath, rootPath);
        const name = ep.className ? `${ep.className}.${ep.name}` : ep.name;
        lines.push(`| \`${repoText(name)}\` | \`${repoText(file)}\` | ${ep.fanOut} |`);
      }
      if (cg.entryPoints.length > maxEntryPoints) {
        lines.push(`| … | *(${cg.entryPoints.length - maxEntryPoints} more)* | |`);
      }
      lines.push('');
    }

    // ── Critical hubs ─────────────────────────────────────────────────────────
    if (cg?.hubFunctions?.length) {
      const sorted = [...cg.hubFunctions].sort((a, b) => b.fanIn - a.fanIn);
      lines.push('## Critical hubs');
      lines.push('Most-called functions — modifying these has the widest blast radius.');
      lines.push('');
      lines.push('| Function | File | fanIn | fanOut |');
      lines.push('|----------|------|-------|--------|');
      for (const hub of sorted.slice(0, maxHubs)) {
        const file = rel(hub.filePath, rootPath);
        const name = hub.className ? `${hub.className}.${hub.name}` : hub.name;
        lines.push(`| \`${repoText(name)}\` | \`${repoText(file)}\` | ${hub.fanIn} | ${hub.fanOut} |`);
      }
      if (sorted.length > maxHubs) {
        lines.push(`| … | *(${sorted.length - maxHubs} more)* | | |`);
      }
      lines.push('');
    }

    // ── God functions ─────────────────────────────────────────────────────────
    if (cg?.nodes?.length) {
      // Production functions only — test helpers and external (library) nodes are
      // not orchestrators of this codebase (see Overview note above).
      const gods = cg.nodes
        .filter(n => !n.isTest && !n.isExternal && n.fanOut >= 8)
        .sort((a, b) => b.fanOut - a.fanOut)
        .slice(0, maxGodFunctions);

      if (gods.length > 0) {
        lines.push('## God functions (high fan-out orchestrators)');
        lines.push('These functions coordinate many downstream calls — extend them carefully.');
        lines.push('');
        lines.push('| Function | File | fanOut |');
        lines.push('|----------|------|--------|');
        for (const g of gods) {
          const file = rel(g.filePath, rootPath);
          const name = g.className ? `${g.className}.${g.name}` : g.name;
          lines.push(`| \`${repoText(name)}\` | \`${repoText(file)}\` | ${g.fanOut} |`);
        }
        lines.push('');
      }
    }

    // ── Most coupled files ────────────────────────────────────────────────────
    const coupled = fileCoupling(depGraph);
    if (coupled.length > 0) {
      const top = coupled.filter(f => f.importedBy >= 3).slice(0, maxCoupledFiles);
      if (top.length > 0) {
        lines.push('## Most imported files');
        lines.push('High in-degree files — changes here ripple widely. Prefer extending over modifying.');
        lines.push('');
        lines.push('| File | imported by | imports |');
        lines.push('|------|-------------|---------|');
        for (const f of top) {
          lines.push(`| \`${repoText(f.path)}\` | ${f.importedBy} | ${f.imports} |`);
        }
        lines.push('');
      }
    }

    // ── Layer violations ──────────────────────────────────────────────────────
    if (cg?.layerViolations?.length) {
      lines.push('## Layer violations');
      lines.push('These cross-layer call patterns indicate architecture drift.');
      lines.push('');
      for (const v of cg.layerViolations.slice(0, 5)) {
        lines.push(`- \`${repoText(v.callerId)}\` → \`${repoText(v.calleeId)}\` *(${repoText(v.callerLayer)} → ${repoText(v.calleeLayer)})*`);
      }
      if (cg.layerViolations.length > 5) {
        lines.push(`- … (${cg.layerViolations.length - 5} more violations)`);
      }
      lines.push('');
    }

    // ── Reconciled analysis domains ──────────────────────────────────────────
    if (repoStructure?.domains.length) {
      const raw = repoStructure.statistics.rawDomainCandidateCount ?? repoStructure.domains.length;
      lines.push('## Inferred ownership domains');
      lines.push(`${raw} raw candidates reconciled into ${repoStructure.domains.length} generation-ready domains.`);
      lines.push('');
      for (const domain of repoStructure.domains) {
        const defining = domain.definingFiles?.length ?? domain.files.length;
        const supporting = domain.supportingFiles?.length ?? 0;
        lines.push(`- \`${repoText(domain.name)}\` — ${defining} defining, ${supporting} supporting files`);
      }
      lines.push('');
    }

    // ── Spec domains ──────────────────────────────────────────────────────────
    const specsDir = join(rootPath, 'openspec', 'specs');
    if (existsSync(specsDir)) {
      try {
        const entries = await readdir(specsDir);
        // Sort before emission: raw `readdir` order is platform-dependent, so an
        // unsorted list would make the digest bytes vary across machines.
        const domains = entries
          .filter(e => existsSync(join(specsDir, e, 'spec.md')))
          .sort((a, b) => a.localeCompare(b));
        if (domains.length > 0) {
          lines.push('## Spec domains');
          lines.push('OpenSpec domains available for this project. Use `search_specs` or `get_spec` to query them.');
          lines.push('');
          for (const d of domains) {
            lines.push(`- \`${repoText(d)}\` — \`openspec/specs/${repoText(d)}/spec.md\``);
          }
          lines.push('');
        }
      } catch { /* non-fatal */ }
    }

    // ── MCP workflow ─────────────────────────────────────────────────────────────────────────────
    const bodyEnd = lines.length;
    lines.push('## openlore MCP workflow');
    lines.push('');
    lines.push('**Follow this sequence for every task:**');
    lines.push('');
    lines.push('1. **`orient "<task description>"`** — always start here. Returns relevant functions, files, spec domains, call paths, and insertion points in one call.');
    lines.push('2. **If the task involves data models, APIs, or config** — call the relevant inventory tool:');
    lines.push('   `get_schema_inventory` · `get_route_inventory` · `get_env_vars` · `get_ui_component_inventory` · `get_middleware_inventory`');
    lines.push('3. **If debugging a call flow** ("how does X reach Y?") — `trace_execution_path`');
    lines.push('4. **Before modifying a function** — `get_subgraph` to understand blast radius');
    lines.push('5. **Before opening a PR** — `check_spec_drift`');
    lines.push('');
    lines.push("**On-demand** (when orient's results aren't enough):");
    lines.push('`search_code` · `suggest_insertion_points` · `get_spec <domain>` · `search_specs` · `analyze_impact` · `get_function_body` · `get_function_skeleton`');

    const digest = [
      ...lines.slice(0, bodyStart),
      frameServedContent(lines.slice(bodyStart, bodyEnd).join('\n'), 'source-derived', 'codebase digest'),
      '',
      ...lines.slice(bodyEnd),
    ].join('\n') + '\n';
    // `writeFile` FOLLOWED a symlink at this path. A repository committing
    // `.openlore/analysis/CODEBASE.md -> ~/.claude/CLAUDE.md` therefore had repo-chosen text
    // (directory-derived domain names, function names) written straight into the developer's
    // GLOBAL agent instructions by a plain `openlore install`. The confined atomic writer refuses
    // a non-regular target and a symlinked path component, like every other artifact in the tree.
    await confinedAtomicWriteFile(outputDir, join(outputDir, 'CODEBASE.md'), digest);
    return true;
  } catch {
    return false;
  }
}
