import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mkdtemp, mkdir, readFile, readdir, stat, symlink, unlink, utimes, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  SpecVectorIndex,
  _resetSpecVectorIndexVerificationCacheForTesting,
} from './spec-vector-index.js';
import type { EmbeddingService } from './embedding-service.js';
import { semanticAnswerBytes } from './derived-artifact-equivalence.js';

// ============================================================================
// FIXTURES
// ============================================================================

const SAMPLE_SPEC_AUTH = `# Auth Specification

> Generated by openlore v1.0.0 on 2026-01-01
> Source files: src/auth/index.ts

## Purpose

Handles user authentication and session management.

## Entities

### User

Represents an authenticated user.

## Requirements

### Requirement: ValidateEmail

The system SHALL validate email format before registration.

#### Scenario: ValidEmail
- **GIVEN** A valid email address
- **WHEN** validateEmail is called
- **THEN** Returns true

#### Scenario: InvalidEmail
- **GIVEN** An invalid email address
- **WHEN** validateEmail is called
- **THEN** Returns false

### Requirement: Login

The system SHALL authenticate users with email and password.

## Design

JWT tokens are used for session management.
`;

const SAMPLE_SPEC_CRAWLER = `# Crawler Specification

## Purpose

Web crawling and content extraction.

## Requirements

### Requirement: Fetch

The system SHALL fetch pages via HTTP with retry logic.
`;

const SAMPLE_MAPPING = JSON.stringify({
  mappings: [
    {
      requirement: 'validateEmail',
      domain: 'auth',
      specFile: './openspec/specs/auth/spec.md',
      functions: [
        { name: 'validateEmail', file: 'src/auth/validator.ts', line: 10, kind: 'function', confidence: 'llm' },
        { name: 'UserService', file: 'src/auth/user.service.ts', line: 1, kind: 'class', confidence: 'heuristic' },
      ],
    },
    {
      requirement: 'login',
      domain: 'auth',
      specFile: './openspec/specs/auth/spec.md',
      functions: [
        { name: '*', file: 'src/auth/index.ts', line: 1, kind: 'unknown', confidence: 'heuristic' },
      ],
    },
    {
      requirement: 'fetch',
      domain: 'crawler',
      specFile: './openspec/specs/crawler/spec.md',
      functions: [
        { name: 'fetchPage', file: 'src/crawler/fetcher.ts', line: 5, kind: 'function', confidence: 'llm' },
      ],
    },
  ],
});

// ============================================================================
// MOCK
// ============================================================================

const DIM = 8;

function makeVector(seed: number): number[] {
  return Array.from({ length: DIM }, (_, i) => ((seed + i) % 10) * 0.1);
}

function makeMockEmbedSvc(): EmbeddingService {
  const callCount = 0;
  return {
    embed: vi.fn().mockImplementation(async (texts: string[]) =>
      // `i++` here incremented the map callback's own index parameter and threw the
      // result away; the expression value is unchanged by dropping it.
      texts.map((_, i) => makeVector(callCount + i))
    ),
  } as unknown as EmbeddingService;
}

// ============================================================================
// HELPERS
// ============================================================================

async function createSpecsDir(
  root: string,
  specs: Record<string, string>
): Promise<string> {
  const specsDir = join(root, 'openspec', 'specs');
  for (const [domain, content] of Object.entries(specs)) {
    const domainDir = join(specsDir, domain);
    await mkdir(domainDir, { recursive: true });
    await writeFile(join(domainDir, 'spec.md'), content, 'utf-8');
  }
  return specsDir;
}

// ============================================================================
// TESTS
// ============================================================================

describe('SpecVectorIndex', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), 'openlore-spec-vector-test-'));
  });

  // --------------------------------------------------------------------------
  // exists()
  // --------------------------------------------------------------------------

  describe('exists()', () => {
    it('returns false when no index has been built', () => {
      expect(SpecVectorIndex.exists(tmpDir)).toBe(false);
    });

    it('returns true after build()', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      expect(SpecVectorIndex.exists(tmpDir)).toBe(true);
    });

    it('keeps a genuinely missing sidecar readable as a legacy index', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, makeMockEmbedSvc());
      await unlink(join(tmpDir, 'spec-index-meta.json'));
      expect(SpecVectorIndex.exists(tmpDir)).toBe(true);
    });

    it('recognizes a valid schema-v1 sidecar as legacy rather than malformed', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, makeMockEmbedSvc());
      await writeFile(join(tmpDir, 'spec-index-meta.json'), JSON.stringify({
        hasEmbeddings: true,
        dim: DIM,
        model: 'legacy-model',
        builtAt: '2026-01-01T00:00:00.000Z',
        schemaVersion: 1,
      }), 'utf-8');
      expect(SpecVectorIndex.exists(tmpDir)).toBe(true);
    });
  });

  // --------------------------------------------------------------------------
  // build()
  // --------------------------------------------------------------------------

  describe('build()', () => {
    it('throws a "present but empty" error when the spec dir exists but has no specs', async () => {
      const emptyDir = join(tmpDir, 'empty-specs');
      await mkdir(emptyDir, { recursive: true });
      const embedSvc = makeMockEmbedSvc();
      await expect(SpecVectorIndex.build(tmpDir, emptyDir, embedSvc)).rejects.toThrow(
        'exists but contains no spec.md files'
      );
    });

    it('fails closed when any authoritative spec is oversized instead of publishing a partial index', async () => {
      const specsDir = await createSpecsDir(tmpDir, {
        auth: SAMPLE_SPEC_AUTH,
        oversized: 'x'.repeat(4 * 1024 * 1024 + 1),
      });
      // The message embeds `relative(specsDir, specFile)` — a HOST filesystem path, where
      // the native separator is correct — so the expectation is built the same way rather
      // than hard-coding the POSIX form.
      await expect(SpecVectorIndex.build(tmpDir, specsDir, null)).rejects.toThrow(
        `Cannot read authoritative spec artifact ${join('oversized', 'spec.md')}`,
      );
    });
  // skipIf(win32): creating a symlink there needs elevated privileges or Developer Mode,
  // so this cannot build the premise it asserts about and would test a plain file instead.
  // What it guards is platform-independent and is exercised on Linux.
    it.skipIf(process.platform === 'win32')('does not follow a spec symlink outside the confined specs directory', async () => {
      const specsDir = join(tmpDir, 'openspec', 'specs');
      const domainDir = join(specsDir, 'escaped');
      const outside = join(tmpDir, 'outside.md');
      await mkdir(domainDir, { recursive: true });
      await writeFile(outside, SAMPLE_SPEC_AUTH, 'utf8');
      await symlink(outside, join(domainDir, 'spec.md'));

      await expect(SpecVectorIndex.build(tmpDir, specsDir, null)).rejects.toThrow(
        'contains no spec.md files',
      );
    });

    it('fails closed instead of silently omitting an oversized authoritative decision', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const decisionsDir = join(tmpDir, 'openspec', 'decisions');
      await mkdir(decisionsDir, { recursive: true });
      await writeFile(join(decisionsDir, 'adr-0001-oversized.md'), 'x'.repeat(4 * 1024 * 1024 + 1));

      await expect(SpecVectorIndex.build(tmpDir, specsDir, null, undefined, decisionsDir))
        .rejects.toThrow(/Cannot read authoritative decision artifact adr-0001-oversized\.md/);
    });
  // skipIf(win32): creating a symlink there needs elevated privileges or Developer Mode,
  // so this cannot build the premise it asserts about and would test a plain file instead.
  // What it guards is platform-independent and is exercised on Linux.
    it.skipIf(process.platform === 'win32')('does not follow an ADR symlink outside the confined decisions directory', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const decisionsDir = join(tmpDir, 'openspec', 'decisions');
      const outside = join(tmpDir, 'outside-adr.md');
      await mkdir(decisionsDir, { recursive: true });
      await writeFile(outside, '# ADR-1: Escaped\n\noutside secret', 'utf8');
      await symlink(outside, join(decisionsDir, 'adr-0001-escaped.md'));
      const baseline = await SpecVectorIndex.build(tmpDir, specsDir, null);

      const rebuilt = await SpecVectorIndex.build(tmpDir, specsDir, null, undefined, decisionsDir);
      expect(rebuilt.recordCount).toBe(baseline.recordCount);
    });

    it('throws a "does not exist" error when the spec dir is missing', async () => {
      const embedSvc = makeMockEmbedSvc();
      await expect(
        SpecVectorIndex.build(tmpDir, join(tmpDir, 'nope-specs'), embedSvc)
      ).rejects.toThrow('does not exist');
    });

    it('returns the number of indexed sections', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      const { recordCount } = await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      // auth spec has: purpose, entities, requirements (2 items), design = 5 sections
      expect(recordCount).toBeGreaterThan(0);
    });

    it('calls embed once with all section texts', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      expect(embedSvc.embed).toHaveBeenCalledTimes(1);
    });

    it('handles multiple domains', async () => {
      const specsDir = await createSpecsDir(tmpDir, {
        auth: SAMPLE_SPEC_AUTH,
        crawler: SAMPLE_SPEC_CRAWLER,
      });
      const embedSvc = makeMockEmbedSvc();
      const { recordCount } = await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      expect(recordCount).toBeGreaterThan(3); // both specs contribute sections
    });

    it('enriches records with linkedFiles from mapping.json', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const mappingPath = join(tmpDir, 'mapping.json');
      await writeFile(mappingPath, SAMPLE_MAPPING, 'utf-8');

      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc, mappingPath);

      // Search for the validateEmail requirement
      const results = await SpecVectorIndex.search(tmpDir, 'email validation', embedSvc, { limit: 20 });
      const emailReq = results.find(r => r.record.id === 'auth.validateEmail');
      expect(emailReq).toBeDefined();
      expect(emailReq!.record.linkedFiles).toContain('src/auth/validator.ts');
      expect(emailReq!.record.linkedFiles).toContain('src/auth/user.service.ts');
    });

    it('filters out wildcard (*) entries from linkedFiles', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const mappingPath = join(tmpDir, 'mapping.json');
      await writeFile(mappingPath, SAMPLE_MAPPING, 'utf-8');

      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc, mappingPath);

      const results = await SpecVectorIndex.search(tmpDir, 'login authentication', embedSvc, { limit: 20 });
      const loginReq = results.find(r => r.record.id === 'auth.login');
      // login mapping only has wildcard (*) → linkedFiles should be empty
      expect(loginReq?.record.linkedFiles ?? []).not.toContain('*');
    });

    it('overwrites existing index on second build', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      await expect(SpecVectorIndex.build(tmpDir, specsDir, embedSvc)).resolves.not.toThrow();
      expect(embedSvc.embed).toHaveBeenCalledTimes(1);
    });

    it('rebuilds after a size- and mtime-preserving spec content rewrite', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const specPath = join(specsDir, 'auth', 'spec.md');
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      const beforeMeta = JSON.parse(await readFile(join(tmpDir, 'spec-index-meta.json'), 'utf-8')) as {
        recordsDigest: string;
      };
      const beforeStat = await stat(specPath);
      const rewritten = SAMPLE_SPEC_AUTH.replace('ValidateEmail', 'SanitizeEmail');
      expect(Buffer.byteLength(rewritten)).toBe(Buffer.byteLength(SAMPLE_SPEC_AUTH));
      await writeFile(specPath, rewritten, 'utf-8');
      await utimes(specPath, beforeStat.atime, beforeStat.mtime);

      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const afterMeta = JSON.parse(await readFile(join(tmpDir, 'spec-index-meta.json'), 'utf-8')) as {
        recordsDigest: string;
      };
      expect(embedSvc.embed).toHaveBeenCalledTimes(2);
      expect(afterMeta.recordsDigest).not.toBe(beforeMeta.recordsDigest);
    });

    it.each([
      ['malformed JSON', '{'],
      ['wrong-shaped JSON', JSON.stringify({ hasEmbeddings: true })],
    ])('invalidates and rebuilds an index with %s metadata', async (_description, metadata) => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      const baseline = await SpecVectorIndex.search(tmpDir, 'email validation', embedSvc, { limit: 20 });
      await writeFile(join(tmpDir, 'spec-index-meta.json'), metadata, 'utf-8');
      expect(SpecVectorIndex.exists(tmpDir)).toBe(false);

      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      expect(embedSvc.embed).toHaveBeenCalledTimes(3); // initial build + baseline query + repair build
      expect(SpecVectorIndex.exists(tmpDir)).toBe(true);
      const repaired = JSON.parse(await readFile(join(tmpDir, 'spec-index-meta.json'), 'utf-8')) as Record<string, unknown>;
      expect(repaired).toMatchObject({ schemaVersion: 2, recordCount: expect.any(Number) });
      expect(repaired.recordsDigest).toMatch(/^[a-f0-9]{64}$/);
      expect(semanticAnswerBytes(await SpecVectorIndex.search(tmpDir, 'email validation', embedSvc, { limit: 20 })))
        .toBe(semanticAnswerBytes(baseline));
    });

    it('rebuilds instead of reusing a table whose persisted content was rewritten', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      const { connect } = await import('@lancedb/lancedb');
      const db = await connect(join(tmpDir, 'vector-index'));
      const table = await db.openTable('specs');
      const rows = await table.query().toArray() as Record<string, unknown>[];
      await table.update({
        where: `\`id\` = '${String(rows[0].id).replaceAll("'", "''")}'`,
        values: { text: `${String(rows[0].text)} tampered` },
      });

      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      expect(embedSvc.embed).toHaveBeenCalledTimes(2);
      const repairedRows = await (await db.openTable('specs')).query().toArray() as Record<string, unknown>[];
      expect(repairedRows.some(row => String(row.text).endsWith(' tampered'))).toBe(false);
    });

    it('rebuilds instead of reusing a table whose dense vector was rewritten', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      const { connect } = await import('@lancedb/lancedb');
      const db = await connect(join(tmpDir, 'vector-index'));
      const table = await db.openTable('specs');
      const [first] = await table.query().limit(1).toArray() as Record<string, unknown>[];
      await table.update({
        where: `\`id\` = '${String(first.id).replaceAll("'", "''")}'`,
        values: { vector: new Array(DIM).fill(0.875) },
      });

      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      expect(embedSvc.embed).toHaveBeenCalledTimes(2);
    });

    it('does not repeat the full integrity scan for unchanged warm searches', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      _resetSpecVectorIndexVerificationCacheForTesting();

      const { connect } = await import('@lancedb/lancedb');
      const table = await (await connect(join(tmpDir, 'vector-index'))).openTable('specs');
      const querySpy = vi.spyOn(Object.getPrototypeOf(table) as { query(): unknown }, 'query');

      await SpecVectorIndex.search(tmpDir, 'email', embedSvc);
      await SpecVectorIndex.search(tmpDir, 'authentication', embedSvc);

      // First search: one full integrity scan + one ANN query. Second search:
      // one ANN query only because metadata and every Lance table file are unchanged.
      expect(querySpy).toHaveBeenCalledTimes(3);
      querySpy.mockRestore();
    });

    it('invalidates warm verification when Lance publishes a new table version', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      _resetSpecVectorIndexVerificationCacheForTesting();

      const { connect } = await import('@lancedb/lancedb');
      const table = await (await connect(join(tmpDir, 'vector-index'))).openTable('specs');
      const querySpy = vi.spyOn(Object.getPrototypeOf(table) as { query(): unknown }, 'query');
      await SpecVectorIndex.search(tmpDir, 'email', embedSvc);

      const [first] = await table.query().limit(1).toArray() as Record<string, unknown>[];
      await table.update({
        where: `\`id\` = '${String(first.id).replaceAll("'", "''")}'`,
        values: { text: `${String(first.text)} tampered` },
      });

      await expect(SpecVectorIndex.search(tmpDir, 'authentication', embedSvc))
        .rejects.toThrow(/content does not match its metadata/);
      // First search scans + ANN; after the constant-cost version changes, the
      // second request performs one integrity scan and fails before ANN serving.
      expect(querySpy).toHaveBeenCalledTimes(4);
      querySpy.mockRestore();
    });

    it('publishes metadata atomically without leaving a sibling temp file', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, makeMockEmbedSvc());
      const entries = await readdir(tmpDir);
      expect(entries).toContain('spec-index-meta.json');
      expect(entries.some(entry => entry.startsWith('.spec-index-meta.json.tmp-'))).toBe(false);
    });

    it('proceeds without enrichment if mapping.json is missing', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      const { recordCount } = await SpecVectorIndex.build(
        tmpDir,
        specsDir,
        embedSvc,
        join(tmpDir, 'nonexistent-mapping.json')
      );
      expect(recordCount).toBeGreaterThan(0);
    });
  });

  // --------------------------------------------------------------------------
  // search()
  // --------------------------------------------------------------------------

  describe('search()', () => {
    it.each([
      ['missing', null],
      ['schema-v1 claiming embeddings', {
        hasEmbeddings: true,
        dim: DIM,
        model: 'legacy-model',
        builtAt: '2026-01-01T00:00:00.000Z',
        schemaVersion: 1,
      }],
    ])('probes a BM25-only table when metadata is %s before selecting ANN', async (_label, legacyMeta) => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      const metaPath = join(tmpDir, 'spec-index-meta.json');
      if (legacyMeta === null) await unlink(metaPath);
      else await writeFile(metaPath, JSON.stringify(legacyMeta), 'utf8');

      const results = await SpecVectorIndex.search(tmpDir, 'validate email', makeMockEmbedSvc());
      expect(results.some(result => result.record.id === 'auth.validateEmail')).toBe(true);
    });
    it('returns up to limit results', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any query', embedSvc, { limit: 2 });
      expect(results.length).toBeLessThanOrEqual(2);
    });

    it('bounds BM25 diagnostic trace candidates to the ordinary oversample window', async () => {
      const requirements = Array.from({ length: 12 }, (_, i) =>
        `### Requirement: Common${i}\n\nThe system SHALL handle common behavior ${i}.`,
      ).join('\n\n');
      const specsDir = await createSpecsDir(tmpDir, {
        common: `# Common\n\n## Requirements\n\n${requirements}\n`,
      });
      await SpecVectorIndex.build(tmpDir, specsDir, null);

      const results = await SpecVectorIndex.search(tmpDir, 'common', null, {
        limit: 2,
        traceCandidates: true,
      });
      expect(results).toHaveLength(6);
    });

    it('each result has a score field', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'email', embedSvc, { limit: 10 });
      for (const r of results) {
        expect(typeof r.score).toBe('number');
        expect(r.scoreKind).toBe('cosine_distance');
        expect(r.matchEvidence).toEqual({ field: 'vector', terms: [], tier: 3 });
      }
    });

    it('labels keyword results as higher-is-better BM25 scores', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);

      const results = await SpecVectorIndex.search(tmpDir, 'email', null, { limit: 10 });

      expect(results.length).toBeGreaterThan(0);
      expect(results.every(result => result.scoreKind === 'bm25')).toBe(true);
    });

    it('uses cosine distance when dense results are labeled cosine_distance', async () => {
      const specsDir = await createSpecsDir(tmpDir, {
        auth: SAMPLE_SPEC_AUTH,
        crawler: SAMPLE_SPEC_CRAWLER,
      });
      let call = 0;
      const embedSvc = {
        modelName: 'cosine-test',
        embed: vi.fn().mockImplementation(async (texts: string[]) => {
          call++;
          return call === 1
            ? texts.map((_, index) => index === 0 ? [1, 0] : [0, 1])
            : [[10, 0]];
        }),
      } as unknown as EmbeddingService;
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'query', embedSvc, { limit: 1 });

      expect(results[0].scoreKind).toBe('cosine_distance');
      expect(results[0].score).toBeCloseTo(0, 5);
    });

    it('falls back to BM25 when a same-dimension query embedder uses another model', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const indexEmbedder = {
        ...makeMockEmbedSvc(),
        modelName: 'model-a',
      } as unknown as EmbeddingService;
      const queryEmbedder = {
        ...makeMockEmbedSvc(),
        modelName: 'model-b',
      } as unknown as EmbeddingService;
      await SpecVectorIndex.build(tmpDir, specsDir, indexEmbedder);

      const results = await SpecVectorIndex.search(tmpDir, 'email', queryEmbedder, { limit: 10 });

      expect(queryEmbedder.embed).not.toHaveBeenCalled();
      expect(results.length).toBeGreaterThan(0);
      expect(results.every(result => result.scoreKind === 'bm25')).toBe(true);
    });

    it('returns an exact count with a bounded path list after more than 1,000 changes', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      await SpecVectorIndex.noteSpecFilesChanged(
        tmpDir,
        Array.from({ length: 1_001 }, (_, index) => `openspec/specs/domain-${index}/spec.md`),
      );

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'tracked',
        changedFileCount: 1_001,
        changedFilesTruncated: true,
      });
      expect((await SpecVectorIndex.freshness(tmpDir))?.changedFiles).toHaveLength(1_000);
    });

    it('keeps freshness unavailable after the receipt exceeds its storage bound', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      await SpecVectorIndex.noteSpecFilesChanged(
        tmpDir,
        Array.from(
          { length: 400 },
          (_, index) => `openspec/specs/${index}-${'x'.repeat(900)}/spec.md`,
        ),
      );

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'unavailable',
        changedFileCount: null,
      });
      expect((await stat(join(tmpDir, 'spec-index-freshness.json'))).size).toBeLessThan(1_000);

      await SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/specs/new/spec.md']);
      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'unavailable',
        changedFileCount: null,
      });
    });

    it('keeps freshness unavailable when the receipt is missing before an edit', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      await unlink(join(tmpDir, 'spec-index-freshness.json'));

      await SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/specs/auth/spec.md']);

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'unavailable',
        changedFileCount: null,
      });
    });

    it('keeps freshness unavailable when the receipt belongs to an older build', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      await writeFile(join(tmpDir, 'spec-index-freshness.json'), JSON.stringify({
        schemaVersion: 1,
        indexBuiltAt: '2026-01-01T00:00:00.000Z',
        changedFiles: ['openspec/specs/old/spec.md'],
      }));

      await SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/specs/auth/spec.md']);

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'unavailable',
        changedFileCount: null,
      });
    });

    it('prefilters ANN recall so a domain match below the old fetch horizon is returned', async () => {
      const specs = Object.fromEntries([
        ...Array.from({ length: 29 }, (_, i) => [
          `other-${i}`,
          `# Other ${i}\n\n## Purpose\n\nShared query text ${i}.\n`,
        ]),
        ['target', '# Target\n\n## Purpose\n\nShared query text target.\n'],
      ]);
      const specsDir = await createSpecsDir(tmpDir, specs);
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'query', embedSvc, {
        limit: 1,
        domain: 'target',
      });

      expect(results).toHaveLength(1);
      expect(results[0].record.domain).toBe('target');
      expect(results[0].scoreKind).toBe('cosine_distance');
    });

    it('tracks changed spec files against the current index build', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);

      await SpecVectorIndex.noteSpecFilesChanged(tmpDir, [
        'openspec/specs/auth/spec.md',
        'openspec/specs/auth/spec.md',
      ]);

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        changedFileCount: 1,
        changedFiles: ['openspec/specs/auth/spec.md'],
      });
    });

    it('merges concurrent watcher receipts without losing paths', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);

      await Promise.all([
        SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/specs/auth/spec.md']),
        SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/decisions/adr-0001.md']),
      ]);

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        changedFileCount: 2,
        changedFiles: [
          'openspec/decisions/adr-0001.md',
          'openspec/specs/auth/spec.md',
        ],
      });
    });

    it('records an edit that arrives while the initial index build is publishing', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      let releaseEmbed!: () => void;
      let markEmbedStarted!: () => void;
      const embedStarted = new Promise<void>(resolve => { markEmbedStarted = resolve; });
      const embedGate = new Promise<void>(resolve => { releaseEmbed = resolve; });
      const embedSvc = {
        modelName: 'test-model',
        embed: vi.fn().mockImplementation(async (texts: string[]) => {
          markEmbedStarted();
          await embedGate;
          return texts.map((_, index) => makeVector(index));
        }),
      } as unknown as EmbeddingService;

      const build = SpecVectorIndex.build(tmpDir, specsDir, embedSvc);
      await embedStarted;
      const note = SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/specs/auth/spec.md']);
      releaseEmbed();
      await Promise.all([build, note]);

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        changedFileCount: 1,
        changedFiles: ['openspec/specs/auth/spec.md'],
      });
    });

    it('returns search results and freshness from the rebuilt generation after lock contention', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const initialEmbedder = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, initialEmbedder);

      let releaseRebuild!: () => void;
      let markRebuildStarted!: () => void;
      const rebuildStarted = new Promise<void>(resolve => { markRebuildStarted = resolve; });
      const rebuildGate = new Promise<void>(resolve => { releaseRebuild = resolve; });
      const rebuildEmbedder = {
        modelName: 'rebuild-model',
        embed: vi.fn().mockImplementation(async (texts: string[]) => {
          markRebuildStarted();
          await rebuildGate;
          return texts.map((_, index) => makeVector(index));
        }),
      } as unknown as EmbeddingService;
      const searchEmbedder = makeMockEmbedSvc();

      const rebuild = SpecVectorIndex.build(tmpDir, specsDir, rebuildEmbedder);
      await rebuildStarted;
      const search = SpecVectorIndex.searchWithFreshness(tmpDir, 'email', searchEmbedder);
      await new Promise(resolve => setTimeout(resolve, 20));

      releaseRebuild();
      await rebuild;
      const rebuiltMeta = JSON.parse(await readFile(join(tmpDir, 'spec-index-meta.json'), 'utf8')) as {
        builtAt: string;
      };
      const snapshot = await search;
      expect(snapshot.indexFreshness?.builtAt).toBe(rebuiltMeta.builtAt);
    });

    it('clears tracked changes after a verified no-op rebuild', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      await SpecVectorIndex.noteSpecFilesChanged(tmpDir, ['openspec/specs/auth/spec.md']);

      await SpecVectorIndex.build(tmpDir, specsDir, null);

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'tracked',
        changedFileCount: 0,
        changedFiles: [],
      });
    });

    it('reports tracking unavailable when a legacy table has no metadata', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      await unlink(join(tmpDir, 'spec-index-meta.json'));

      expect(await SpecVectorIndex.freshness(tmpDir)).toEqual({
        builtAt: null,
        tracking: 'unavailable',
        changedFileCount: null,
        changedFiles: [],
      });
    });

    it('rejects unsafe paths in a hand-edited freshness receipt', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      const meta = JSON.parse(await readFile(join(tmpDir, 'spec-index-meta.json'), 'utf8')) as {
        builtAt: string;
      };
      await writeFile(join(tmpDir, 'spec-index-freshness.json'), JSON.stringify({
        schemaVersion: 1,
        indexBuiltAt: meta.builtAt,
        changedFiles: ['../outside.md'],
      }));

      expect(await SpecVectorIndex.freshness(tmpDir)).toMatchObject({
        tracking: 'unavailable',
        changedFileCount: null,
        changedFiles: [],
      });
    });

    it('result records have linkedFiles as string[]', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'query', embedSvc, { limit: 10 });
      for (const r of results) {
        expect(Array.isArray(r.record.linkedFiles)).toBe(true);
      }
    });

    it('filters by domain', async () => {
      const specsDir = await createSpecsDir(tmpDir, {
        auth: SAMPLE_SPEC_AUTH,
        crawler: SAMPLE_SPEC_CRAWLER,
      });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any', embedSvc, {
        limit: 20,
        domain: 'auth',
      });
      for (const r of results) {
        expect(r.record.domain).toBe('auth');
      }
    });

    it('filters by section', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any', embedSvc, {
        limit: 20,
        section: 'requirements',
      });
      for (const r of results) {
        expect(r.record.section).toBe('requirements');
      }
    });

    it('throws when index does not exist', async () => {
      const embedSvc = makeMockEmbedSvc();
      await expect(
        SpecVectorIndex.search(tmpDir, 'query', embedSvc, { limit: 5 })
      ).rejects.toThrow('No spec index found');
      expect(embedSvc.embed).not.toHaveBeenCalled();
    });

    it('invalidates persisted table content that disagrees with current metadata', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      await SpecVectorIndex.build(tmpDir, specsDir, null);
      const { connect } = await import('@lancedb/lancedb');
      const table = await (await connect(join(tmpDir, 'vector-index'))).openTable('specs');
      const [first] = await table.query().limit(1).toArray() as Record<string, unknown>[];
      await table.update({
        where: `\`id\` = '${String(first.id).replaceAll("'", "''")}'`,
        values: { text: `${String(first.text)} tampered` },
      });

      await expect(SpecVectorIndex.search(tmpDir, 'tampered', null)).rejects.toThrow(
        'Spec index content does not match its metadata',
      );
    });

    it('returns empty array when domain filter matches nothing', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'any', embedSvc, {
        limit: 20,
        domain: 'nonexistent-domain',
      });
      expect(results).toHaveLength(0);
    });
  });

  // --------------------------------------------------------------------------
  // Markdown parser (tested indirectly via build + search)
  // --------------------------------------------------------------------------

  describe('Markdown parsing', () => {
    it('assigns correct section type to Requirements H3 items', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'validate email', embedSvc, {
        limit: 20,
        section: 'requirements',
      });
      expect(results.length).toBeGreaterThan(0);
      const req = results.find(r => r.record.id.includes('validateEmail'));
      expect(req).toBeDefined();
      expect(req!.record.section).toBe('requirements');
    });

    it('assigns correct section type to Purpose H2', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'authentication session', embedSvc, {
        limit: 20,
        section: 'purpose',
      });
      expect(results.length).toBeGreaterThan(0);
    });

    it('builds id as domain.requirementKey for requirements', async () => {
      const specsDir = await createSpecsDir(tmpDir, { auth: SAMPLE_SPEC_AUTH });
      const embedSvc = makeMockEmbedSvc();
      await SpecVectorIndex.build(tmpDir, specsDir, embedSvc);

      const results = await SpecVectorIndex.search(tmpDir, 'validate', embedSvc, { limit: 20 });
      const req = results.find(r => r.record.id === 'auth.validateEmail');
      expect(req).toBeDefined();
    });
  });
});
