/**
 * OpenSpec Writer Tests
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdir, rm, writeFile, readFile, readdir, access, symlink } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import {
  OpenSpecWriter,
  writeOpenSpecs,
  initializeOpenSpec,
  shouldCleanStaleDomains,
} from './openspec-writer.js';
import type { GeneratedSpec } from './openspec-format-generator.js';
import type { ProjectSurveyResult } from './spec-pipeline.js';
import { OPENLORE_PACKAGE_VERSION } from '../runtime/package-versions.js';
import { createRequire } from 'node:module';

// The report echoes the OpenSpec version actually installed. Deriving the
// expectation from the pinned devDependency keeps this true across bumps
// instead of breaking on every OpenSpec release.
const OPENSPEC_PINNED_VERSION = (
  createRequire(import.meta.url)('../../../package.json') as { devDependencies: Record<string, string> }
).devDependencies['@fission-ai/openspec'];


// ============================================================================
// TEST HELPERS
// ============================================================================

async function createTempDir(): Promise<string> {
  const dir = join(tmpdir(), `openspec-writer-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  await mkdir(dir, { recursive: true });
  return dir;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function createMockSurvey(): ProjectSurveyResult {
  return {
    projectCategory: 'web-backend',
    primaryLanguage: 'TypeScript',
    frameworks: ['Express', 'TypeORM'],
    architecturePattern: 'layered',
    domainSummary: 'A user management API service',
    suggestedDomains: ['user', 'auth'],
    confidence: 0.85,
    schemaFiles: [],
    serviceFiles: [],
    apiFiles: [],
  };
}

function createMockSpecs(): GeneratedSpec[] {
  return [
    {
      path: 'openspec/specs/overview/spec.md',
      content: `# System Overview

> Generated by openlore v1.0.0 on 2024-01-01
> Confidence: 85%

## Purpose

A user management API service.

## Domains

| Domain | Description | Spec |
|--------|-------------|------|
| User | Manages user entities | [spec.md](../user/spec.md) |
`,
      domain: 'overview',
      type: 'overview',
    },
    {
      path: 'openspec/specs/user/spec.md',
      content: `# User Specification

> Generated by openlore v1.0.0 on 2024-01-01

## Purpose

Manages user data and authentication.

## Requirements

### Requirement: UserValidation

The system SHALL validate all user input.

#### Scenario: ValidUser
- **GIVEN** valid user data
- **WHEN** validation is performed
- **THEN** validation succeeds
`,
      domain: 'user',
      type: 'domain',
    },
    {
      path: 'openspec/specs/architecture/spec.md',
      content: `# Architecture Specification

> Generated by openlore v1.0.0 on 2024-01-01

## Purpose

System architecture documentation.

## Architecture Style

Layered architecture.
`,
      domain: 'architecture',
      type: 'architecture',
    },
  ];
}

// ============================================================================
// TESTS
// ============================================================================

// Structural guard (mcp-security: Spec-Generation Writer Confines LLM-Derived Paths;
// GHSA-5j8x-q7q6-58j5). The spec-generation writer is the one LLM-in-the-loop write
// surface, and it sits outside the MCP path-parameter coverage gate. This gate is its
// equivalent: it fails if `writeSpec` ever stops confining the (LLM-derived) spec path
// through `safeJoin`, or reverts to a vulnerable bare path join
// — so a future edit cannot silently reopen the traversal.
describe('Write confinement structural guard (mcp-security)', () => {
  const writerSrc = readFileSync(
    fileURLToPath(new URL('./openspec-writer.ts', import.meta.url)),
    'utf-8',
  );

  it('imports the shared path-confinement guard', () => {
    expect(writerSrc).toMatch(/import\s*\{[^}]*\bsafeJoin\b[^}]*\}\s*from\s*['"][^'"]*path-confinement/);
  });

  it('confines the spec write path through safeJoin', () => {
    expect(
      /safeJoin\(\s*this\.openspecRoot\s*,\s*spec\.path\.slice\(prefix\.length\)\s*\)/.test(writerSrc),
      'writeSpec must strip the openspec/ prefix and resolve within this.openspecRoot via safeJoin',
    ).toBe(true);
  });

  it('never resolves the untrusted spec path with a bare path.join (the pre-fix sink)', () => {
    // `safeJoin(...)` carries a capital J, so this lowercase-j pattern matches only a
    // reverted bare `join(this.rootPath, spec.path)`, not the confined call.
    expect(
      /\bjoin\(\s*this\.rootPath\s*,\s*spec\.path\s*\)/.test(writerSrc),
      'writeSpec must not resolve the untrusted spec.path with an unconfined path.join',
    ).toBe(false);
  });
});

describe('OpenSpecWriter', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir();
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  describe('initialize', () => {
    it('should create OpenSpec directory structure', async () => {
      const writer = new OpenSpecWriter({ rootPath: tempDir });

      await writer.initialize();

      expect(await fileExists(join(tempDir, 'openspec', 'specs'))).toBe(true);
      expect(await fileExists(join(tempDir, 'openspec', 'changes', 'archive'))).toBe(true);
      expect(await fileExists(join(tempDir, '.openlore', 'analysis'))).toBe(true);
      expect(await fileExists(join(tempDir, '.openlore', 'backups'))).toBe(true);
      expect(await fileExists(join(tempDir, '.openlore', 'outputs'))).toBe(true);
      expect(await fileExists(join(tempDir, '.openlore', 'logs'))).toBe(true);
    });
  });

  describe('writeSpecs', () => {
    it('writes specs and config to an explicit OpenSpec root outside the project root', async () => {
      const openspecRoot = await createTempDir();
      try {
        const writer = new OpenSpecWriter({ rootPath: tempDir, openspecRoot, updateConfig: true });
        await writer.writeSpecs(createMockSpecs(), createMockSurvey());
        expect(await fileExists(join(openspecRoot, 'specs/user/spec.md'))).toBe(true);
        expect(await fileExists(join(openspecRoot, 'config.yaml'))).toBe(true);
        expect(await fileExists(join(tempDir, 'openspec/specs/user/spec.md'))).toBe(false);
      } finally {
        await rm(openspecRoot, { recursive: true, force: true });
      }
    });

    it('merges an existing spec under an external OpenSpec root and keeps backups project-local', async () => {
      const openspecRoot = await createTempDir();
      try {
        await mkdir(join(openspecRoot, 'specs/user'), { recursive: true });
        await writeFile(join(openspecRoot, 'specs/user/spec.md'), '# User\n\nHuman preface.\n');
        const writer = new OpenSpecWriter({
          rootPath: tempDir,
          openspecRoot,
          writeMode: 'merge',
          updateConfig: false,
        });

        const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

        expect(report.filesMerged).toContain('openspec/specs/user/spec.md');
        expect(await readFile(join(openspecRoot, 'specs/user/spec.md'), 'utf-8')).toContain('Human preface.');
        const backup = report.filesBackedUp.find(path => path.endsWith('openspec/specs/user/spec.md'));
        expect(backup).toBeDefined();
        expect(await fileExists(join(tempDir, backup!))).toBe(true);
      } finally {
        await rm(openspecRoot, { recursive: true, force: true });
      }
    });

    it('should write all specs to correct paths', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        version: '1.0.0',
        updateConfig: false,
      });
      const specs = createMockSpecs();
      const survey = createMockSurvey();

      const report = await writer.writeSpecs(specs, survey);

      expect(report.filesWritten).toHaveLength(3);
      expect(await fileExists(join(tempDir, 'openspec/specs/overview/spec.md'))).toBe(true);
      expect(await fileExists(join(tempDir, 'openspec/specs/user/spec.md'))).toBe(true);
      expect(await fileExists(join(tempDir, 'openspec/specs/architecture/spec.md'))).toBe(true);
    });

    it('should write correct content', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        updateConfig: false,
      });
      const specs = createMockSpecs();
      const survey = createMockSurvey();

      await writer.writeSpecs(specs, survey);

      const userSpec = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      expect(userSpec).toContain('# User Specification');
      expect(userSpec).toContain('## Purpose');
      expect(userSpec).toContain('### Requirement: UserValidation');
    });

    it('should save generation report', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        updateConfig: false,
      });
      const specs = createMockSpecs();
      const survey = createMockSurvey();

      await writer.writeSpecs(specs, survey);

      const reportPath = join(tempDir, '.openlore/outputs/generation-report.json');
      expect(await fileExists(reportPath)).toBe(true);

      const report = JSON.parse(await readFile(reportPath, 'utf-8'));
      expect(report.filesWritten).toHaveLength(3);
      expect(report.nextSteps.length).toBeGreaterThan(0);
    });

    it('should include timestamp in report', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    });
  });

  describe('Write Mode: replace (default)', () => {
    it('should backup and replace existing files', async () => {
      // Create existing spec
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        '# Old User Spec\n\nOriginal content'
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'replace',
        createBackups: true,
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      // New content should be written
      const newContent = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      expect(newContent).toContain('# User Specification');
      expect(newContent).not.toContain('Original content');

      // Backup should exist
      expect(report.filesBackedUp.length).toBeGreaterThan(0);
      const backupDir = join(tempDir, '.openlore/backups');
      const backupDirs = await readdir(backupDir);
      expect(backupDirs.length).toBeGreaterThan(0);
    });

    it('should not backup when createBackups is false', async () => {
      // Create existing spec
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        '# Old User Spec'
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'replace',
        createBackups: false,
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.filesBackedUp).toHaveLength(0);
    });
  });

  describe('Write Mode: skip', () => {
    it('should skip existing files', async () => {
      // Create existing spec
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        '# Old User Spec\n\nPreserved content'
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'skip',
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      // Original content should be preserved
      const content = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      expect(content).toContain('Preserved content');

      // Should be in skipped list
      expect(report.filesSkipped).toContain('openspec/specs/user/spec.md');
    });

    it('should write non-existing files', async () => {
      // Create existing spec for user only
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        '# Old User Spec'
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'skip',
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      // Overview should be written (didn't exist)
      expect(report.filesWritten).toContain('openspec/specs/overview/spec.md');
      expect(await fileExists(join(tempDir, 'openspec/specs/overview/spec.md'))).toBe(true);
    });
  });

  describe('Write Mode: merge', () => {
    it('should append generated section to existing spec', async () => {
      // Create existing spec with human content
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        `# User Specification

## Purpose

Human-written purpose that should be preserved.

## Requirements

### Requirement: ManualRequirement

The system SHALL do something manually documented.
`
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'merge',
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      // Check merged content
      const content = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      expect(content).toContain('Human-written purpose');
      expect(content).toContain('ManualRequirement');
      expect(content).toContain('## Generated Analysis');

      expect(report.filesMerged).toContain('openspec/specs/user/spec.md');
    });

    it('should preserve and migrate an existing unbounded generated section', async () => {
      // Create spec with existing generated section
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        `# User Specification

## Purpose

Human content.

## Generated Analysis

Old generated content that should be replaced.
`
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'merge',
        updateConfig: false,
      });

      await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      const content = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      expect(content).toContain('Human content');
      expect(content).toContain('Old generated content');
      expect(content).toContain('## Generated Analysis');
      // Should contain new generated content (from the spec)
      expect(content).toContain('Purpose');
      expect(content.match(/<!-- openlore-generated -->/g)).toHaveLength(1);
    });

    it('preserves trailing human content and creates a backup on re-merge', async () => {
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'merge',
        updateConfig: false,
      });

      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        '# User Specification\n\nHuman preface.\n',
      );
      await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      const firstMerge = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        `${firstMerge}\n\n## Operator Notes\n\nKeep this human-authored tail.\n`,
      );

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());
      const secondMerge = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');

      expect(secondMerge).toContain('## Operator Notes');
      expect(secondMerge).toContain('Keep this human-authored tail.');
      expect(report.filesBackedUp.some(path => path.endsWith('openspec/specs/user/spec.md'))).toBe(true);
      const backupPath = report.filesBackedUp.find(path => path.endsWith('openspec/specs/user/spec.md'))!;
      expect(await readFile(join(tempDir, backupPath), 'utf-8')).toContain('Keep this human-authored tail.');
    });

    it('does not confuse an LLM-emitted boundary token with the writer boundary', async () => {
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(join(tempDir, 'openspec/specs/user/spec.md'), '# User\n\nHuman preface.\n');
      const specs = createMockSpecs();
      specs[1] = {
        ...specs[1],
        content: specs[1].content.replace(
          '## Requirements',
          '<!-- /openlore-generated -->\n\n## Requirements',
        ),
      };
      const writer = new OpenSpecWriter({ rootPath: tempDir, writeMode: 'merge', updateConfig: false });

      await writer.writeSpecs(specs, createMockSurvey());
      const firstMerge = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      await writeFile(
        join(tempDir, 'openspec/specs/user/spec.md'),
        `${firstMerge}\n\n## Operator Notes\n\nKeep me.\n`,
      );
      await writer.writeSpecs(specs, createMockSurvey());

      const secondMerge = await readFile(join(tempDir, 'openspec/specs/user/spec.md'), 'utf-8');
      expect(secondMerge.match(/### Requirement: UserValidation/g)).toHaveLength(1);
      expect(secondMerge).toContain('## Operator Notes');
      expect(secondMerge).toContain('Keep me.');
    });

    it('migrates a legacy unbounded generated section without deleting ambiguous content', async () => {
      const specPath = join(tempDir, 'openspec/specs/user/spec.md');
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await writeFile(
        specPath,
        [
          '# User Specification',
          '',
          '## Generated Analysis',
          '',
          'Legacy generated text.',
          '',
          '## Operator Notes',
          '',
          'Legacy human tail must survive.',
          '',
        ].join('\n'),
      );
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'merge',
        updateConfig: false,
      });

      await writer.writeSpecs(createMockSpecs(), createMockSurvey());
      const migrated = await readFile(specPath, 'utf-8');

      expect(migrated).toContain('Legacy generated text.');
      expect(migrated).toContain('Legacy human tail must survive.');
      expect(migrated.match(/<!-- openlore-generated -->/g)).toHaveLength(1);
      expect(migrated.match(/<!-- \/openlore-generated -->/g)).toHaveLength(1);
    });

    it('preserves human notes that document the closing boundary token', async () => {
      const specPath = join(tempDir, 'openspec/specs/user/spec.md');
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        writeMode: 'merge',
        updateConfig: false,
      });
      await writeFile(specPath, '# User Specification\n\nHuman preface.\n');
      await writer.writeSpecs(createMockSpecs(), createMockSurvey());
      const firstMerge = await readFile(specPath, 'utf-8');
      await writeFile(
        specPath,
        `${firstMerge}\n\n## Operator Notes\n\nBefore literal must survive.\n\n` +
          '`<!-- /openlore-generated -->`\n\nAfter literal must survive.\n',
      );

      await writer.writeSpecs(createMockSpecs(), createMockSurvey());
      const secondMerge = await readFile(specPath, 'utf-8');

      expect(secondMerge).toContain('Before literal must survive.');
      expect(secondMerge).toContain('After literal must survive.');
      expect(secondMerge).toContain('`<!-- /openlore-generated -->`');
    });
  });

  describe('Stale domain cleanup', () => {
    it('preserves an existing spec byte-for-byte when reconciliation no longer emits that domain', async () => {
      const demotedDir = join(tempDir, 'openspec/specs/legacy-domain');
      const original = '# Legacy Domain\n\nHuman-maintained requirements must survive reclassification.\n';
      await mkdir(demotedDir, { recursive: true });
      await writeFile(join(demotedDir, 'spec.md'), original);

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        cleanBeforeWrite: false,
        updateConfig: false,
      });
      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.domainsRemoved).not.toContain('legacy-domain');
      expect(await readFile(join(demotedDir, 'spec.md'), 'utf-8')).toBe(original);
    });

    it('recursively backs up a stale domain before removing it', async () => {
      const staleDir = join(tempDir, 'openspec/specs/stale');
      await mkdir(join(staleDir, 'notes'), { recursive: true });
      await writeFile(join(staleDir, 'spec.md'), '# Stale');
      await writeFile(join(staleDir, 'notes', 'operator.md'), 'preserve me');

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        cleanBeforeWrite: true,
        updateConfig: false,
      });
      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.domainsRemoved).toContain('stale');
      expect(await fileExists(staleDir)).toBe(false);
      const backupRuns = await readdir(join(tempDir, '.openlore/backups'));
      const backedUpNestedFile = join(
        tempDir,
        '.openlore/backups',
        backupRuns[0],
        'specs/stale/notes/operator.md',
      );
      expect(await readFile(backedUpNestedFile, 'utf-8')).toBe('preserve me');
    });

    it('backs up every stale domain before removing any of them', async () => {
      vi.useFakeTimers();
      vi.setSystemTime(new Date('2026-08-01T18:00:00.000Z'));
      const firstStale = join(tempDir, 'openspec/specs/a-stale');
      const secondStale = join(tempDir, 'openspec/specs/z-stale');
      await mkdir(firstStale, { recursive: true });
      await mkdir(secondStale, { recursive: true });
      await writeFile(join(firstStale, 'spec.md'), '# A');
      await writeFile(join(secondStale, 'spec.md'), '# Z');
      const backupSpecsDir = join(
        tempDir,
        '.openlore/backups/2026-08-01T18-00-00-000Z/specs',
      );
      await mkdir(backupSpecsDir, { recursive: true });
      // Force one recursive backup to fail: its destination is a file.
      await writeFile(join(backupSpecsDir, 'z-stale'), 'not a directory');
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        cleanBeforeWrite: true,
        updateConfig: false,
      });

      try {
        await expect(writer.writeSpecs(createMockSpecs(), createMockSurvey())).rejects.toThrow();
        expect(await readFile(join(firstStale, 'spec.md'), 'utf-8')).toBe('# A');
        expect(await readFile(join(secondStale, 'spec.md'), 'utf-8')).toBe('# Z');
      } finally {
        vi.useRealTimers();
      }
    });

    it('never reports reserved overview and architecture directories as stale domains', async () => {
      await mkdir(join(tempDir, 'openspec/specs/overview'), { recursive: true });
      await mkdir(join(tempDir, 'openspec/specs/architecture'), { recursive: true });
      await writeFile(join(tempDir, 'openspec/specs/overview/spec.md'), '# Old overview');
      await writeFile(join(tempDir, 'openspec/specs/architecture/spec.md'), '# Old architecture');
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        cleanBeforeWrite: true,
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.domainsRemoved).not.toContain('overview');
      expect(report.domainsRemoved).not.toContain('architecture');
      expect(await readFile(join(tempDir, 'openspec/specs/overview/spec.md'), 'utf-8')).toContain('# System Overview');
      expect(await readFile(join(tempDir, 'openspec/specs/architecture/spec.md'), 'utf-8')).toContain('# Architecture Specification');
    });

    it('fails closed before cleanup when the specs directory is a symlink escape', async () => {
      if (process.platform === 'win32') return;
      const outside = await createTempDir();
      await mkdir(join(tempDir, 'openspec'), { recursive: true });
      await mkdir(join(outside, 'victim'), { recursive: true });
      await writeFile(join(outside, 'victim', 'keep.md'), 'must survive');
      await symlink(outside, join(tempDir, 'openspec/specs'));

      try {
        const writer = new OpenSpecWriter({
          rootPath: tempDir,
          cleanBeforeWrite: true,
          updateConfig: false,
        });
        await expect(writer.writeSpecs(createMockSpecs(), createMockSurvey())).rejects.toThrow(/escape|outside/i);
        expect(await readFile(join(outside, 'victim', 'keep.md'), 'utf-8')).toBe('must survive');
      } finally {
        await rm(outside, { recursive: true, force: true });
      }
    });

    it('fails closed when the backup root is a symlink escape', async () => {
      if (process.platform === 'win32') return;
      const outside = await createTempDir();
      await mkdir(join(tempDir, '.openlore'), { recursive: true });
      await symlink(outside, join(tempDir, '.openlore/backups'));

      try {
        expect(() => new OpenSpecWriter({
          rootPath: tempDir,
          cleanBeforeWrite: true,
          updateConfig: false,
        })).not.toThrow();
        const writer = new OpenSpecWriter({
          rootPath: tempDir,
          cleanBeforeWrite: true,
          updateConfig: false,
        });
        const staleDir = join(tempDir, 'openspec/specs/stale');
        await mkdir(staleDir, { recursive: true });
        await writeFile(join(staleDir, 'spec.md'), '# Stale');

        await expect(writer.writeSpecs(createMockSpecs(), createMockSurvey())).rejects.toThrow(/escape|outside/i);
        expect(await readFile(join(staleDir, 'spec.md'), 'utf-8')).toBe('# Stale');
        expect(await readdir(outside)).toHaveLength(0);
      } finally {
        await rm(outside, { recursive: true, force: true });
      }
    });
  });

  describe('Config Update', () => {
    it('should update config.yaml with openlore metadata', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        version: '2.0.0',
        updateConfig: true,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.configUpdated).toBe(true);

      const configPath = join(tempDir, 'openspec/config.yaml');
      const configContent = await readFile(configPath, 'utf-8');
      expect(configContent).toContain('openlore');
      expect(configContent).toContain('version');
      expect(configContent).toContain('domains');
    });

    it('should preserve existing config when updating', async () => {
      // Create existing config
      await mkdir(join(tempDir, 'openspec'), { recursive: true });
      await writeFile(
        join(tempDir, 'openspec/config.yaml'),
        `schema: custom-schema
context: User provided context
rules:
  specs:
    - must-have-purpose
`
      );

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        updateConfig: true,
      });

      await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      const configContent = await readFile(join(tempDir, 'openspec/config.yaml'), 'utf-8');
      expect(configContent).toContain('custom-schema');
      expect(configContent).toContain('must-have-purpose');
      expect(configContent).toContain('openlore');
    });

    it('uses the complete metadata set when writing only a scoped spec set', async () => {
      const allSpecs: GeneratedSpec[] = [
        createMockSpecs()[1],
        {
          path: 'openspec/specs/billing/spec.md',
          content: '# Billing\n\n## Purpose\n\nBilling.',
          domain: 'billing',
          type: 'domain',
        },
      ];
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        updateConfig: true,
      });

      await writer.writeSpecs([allSpecs[0]], createMockSurvey(), allSpecs);

      const configContent = await readFile(join(tempDir, 'openspec/config.yaml'), 'utf-8');
      expect(configContent).toContain('- user');
      expect(configContent).toContain('- billing');
      expect(await fileExists(join(tempDir, 'openspec/specs/billing/spec.md'))).toBe(false);
    });
  });

  describe('Validation', () => {
    it('should validate specs before writing when enabled', async () => {
      const specs: GeneratedSpec[] = [
        {
          path: 'openspec/specs/bad/spec.md',
          content: 'Invalid spec without proper structure',
          domain: 'bad',
          type: 'domain',
        },
      ];

      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        validateBeforeWrite: true,
        updateConfig: false,
      });

      // Should still write but may log warnings
      const report = await writer.writeSpecs(specs, createMockSurvey());

      expect(report.filesWritten).toContain('openspec/specs/bad/spec.md');
      expect(report.validationErrors.some(error => error.startsWith('openspec/specs/bad/spec.md:'))).toBe(true);
      expect(report.nextSteps).toContain('Fix validation errors before using specs');
    });
  });

  describe('getExistingDomains', () => {
    it('should return list of existing domain directories', async () => {
      await mkdir(join(tempDir, 'openspec/specs/user'), { recursive: true });
      await mkdir(join(tempDir, 'openspec/specs/auth'), { recursive: true });
      await mkdir(join(tempDir, 'openspec/specs/overview'), { recursive: true });

      const writer = new OpenSpecWriter({ rootPath: tempDir });
      const domains = await writer.getExistingDomains();

      expect(domains).toContain('user');
      expect(domains).toContain('auth');
      expect(domains).not.toContain('overview'); // Filtered out
    });
  });

  describe('Generation Report', () => {
    it('should include all required fields', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        version: '1.5.0',
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.timestamp).toBeDefined();
      expect(report.openloreVersion).toBe(OPENLORE_PACKAGE_VERSION);
      expect(report.configSchemaVersion).toBe('1.5.0');
      expect(report.openspecVersion).toBe(OPENSPEC_PINNED_VERSION);
      expect(report.filesWritten).toBeDefined();
      expect(report.filesSkipped).toBeDefined();
      expect(report.filesBackedUp).toBeDefined();
      expect(report.filesMerged).toBeDefined();
      expect(report.nextSteps).toBeDefined();
      expect(report.warnings).toBeDefined();
    });

    it('should include appropriate next steps', async () => {
      const writer = new OpenSpecWriter({
        rootPath: tempDir,
        updateConfig: false,
      });

      const report = await writer.writeSpecs(createMockSpecs(), createMockSurvey());

      expect(report.nextSteps.some(s => s.includes('openspec list'))).toBe(true);
      expect(report.nextSteps.some(s => s.includes('validate'))).toBe(true);
      expect(report.nextSteps.some(s => s.includes('verify'))).toBe(true);
    });
  });
});

describe('stale-domain cleanup policy', () => {
  it('cleans only during unfiltered full force generation', () => {
    expect(shouldCleanStaleDomains(true, [], false)).toBe(true);
    expect(shouldCleanStaleDomains(true, ['auth'], false)).toBe(false);
    expect(shouldCleanStaleDomains(true, [], true)).toBe(false);
    expect(shouldCleanStaleDomains(false, [], false)).toBe(false);
  });
});

describe('Convenience Functions', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir();
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  describe('writeOpenSpecs', () => {
    it('should write specs with default options', async () => {
      const specs = createMockSpecs();
      const survey = createMockSurvey();

      const report = await writeOpenSpecs(specs, survey, {
        rootPath: tempDir,
        updateConfig: false,
      });

      expect(report.filesWritten.length).toBeGreaterThan(0);
    });
  });

  describe('initializeOpenSpec', () => {
    it('should initialize directory structure', async () => {
      await initializeOpenSpec(tempDir);

      expect(await fileExists(join(tempDir, 'openspec/specs'))).toBe(true);
      expect(await fileExists(join(tempDir, '.openlore/analysis'))).toBe(true);
    });
  });
});

describe('Edge Cases', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir();
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  it('should handle empty specs array', async () => {
    const writer = new OpenSpecWriter({
      rootPath: tempDir,
      updateConfig: false,
    });

    const report = await writer.writeSpecs([], createMockSurvey());

    expect(report.filesWritten).toHaveLength(0);
    expect(report.nextSteps.length).toBeGreaterThan(0);
  });

  it('should handle special characters in domain names', async () => {
    const specs: GeneratedSpec[] = [
      {
        path: 'openspec/specs/user-profile/spec.md',
        content: '# User Profile\n\n## Purpose\n\nTest.',
        domain: 'user-profile',
        type: 'domain',
      },
    ];

    const writer = new OpenSpecWriter({
      rootPath: tempDir,
      updateConfig: false,
    });

    const report = await writer.writeSpecs(specs, createMockSurvey());

    expect(report.filesWritten).toContain('openspec/specs/user-profile/spec.md');
    expect(await fileExists(join(tempDir, 'openspec/specs/user-profile/spec.md'))).toBe(true);
  });

  // Path-traversal confinement (GHSA-5j8x-q7q6-58j5; mcp-security: Write Confinement).
  // `spec.path`'s domain segment derives from the Stage-3 LLM `domain` field over
  // untrusted repo content, so a traversal value must never escape the project root.
  it('refuses to write a spec whose path escapes the project root', async () => {
    // Escape one level above tempDir (still inside the OS temp dir, so a regression
    // would land here and be caught — not scattered across the filesystem).
    const escapeDirName = `openlore-escape-proof-${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const escaping: GeneratedSpec[] = [
      {
        path: `openspec/specs/../../../${escapeDirName}/spec.md`,
        content: '# Escaped\n\n## Purpose\n\nShould never be written.',
        domain: 'evil',
        type: 'domain',
      },
    ];

    const writer = new OpenSpecWriter({ rootPath: tempDir, updateConfig: false });
    const report = await writer.writeSpecs(escaping, createMockSurvey());

    // The escaping spec is refused, not silently written out of root.
    expect(report.filesWritten).toHaveLength(0);
    expect(report.warnings.some(w => /traversal|escape|outside/i.test(w))).toBe(true);

    // And nothing landed outside the project root.
    const outside = join(tmpdir(), escapeDirName, 'spec.md');
    expect(await fileExists(outside)).toBe(false);
    await rm(join(tmpdir(), escapeDirName), { recursive: true, force: true });
  });

  it('should handle deeply nested paths', async () => {
    const specs: GeneratedSpec[] = [
      {
        path: 'openspec/specs/domain/subdomain/spec.md',
        content: '# Nested Spec\n\n## Purpose\n\nTest.',
        domain: 'subdomain',
        type: 'domain',
      },
    ];

    const writer = new OpenSpecWriter({
      rootPath: tempDir,
      updateConfig: false,
    });

    await writer.writeSpecs(specs, createMockSurvey());

    expect(await fileExists(join(tempDir, 'openspec/specs/domain/subdomain/spec.md'))).toBe(true);
  });
});
