/**
 * MCP tool handler: generate_change_proposal
 *
 * Given a story description (BMAD story, free-form intent, or spec delta request),
 * produces a populated OpenSpec change proposal at openspec/changes/{slug}/proposal.md.
 *
 * The proposal is built from pure structural analysis — no LLM required:
 *   - orient()        → affected functions, spec domains, insertion points
 *   - search_specs()  → existing requirements touched by this change
 *   - analyze_impact()→ risk scores for the top 2 functions
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { validateDirectory } from './utils.js';
import { handleOrient } from './orient.js';
import { handleSearchSpecs } from './semantic.js';
import { handleAnalyzeImpact } from './graph.js';

// ============================================================================
// INTERNAL TYPES  (narrow slices of handler outputs we actually use)
// ============================================================================

interface OrientResult {
  relevantFunctions?: Array<{
    name: string;
    filePath: string;
    score: number;
    fanIn: number;
    fanOut: number;
    isHub: boolean;
    linkedSpecs: Array<{ requirement: string; domain: string }>;
  }>;
  specDomains?: Array<{ domain: string; specFile: string; matchCount: number }>;
  insertionPoints?: Array<{
    rank: number;
    name: string;
    filePath: string;
    role: string;
    strategy: string;
    reason: string;
    score: number;
  }>;
  matchingSpecs?: Array<{ domain: string; section: string; title: string; score: number; text: string }>;
  error?: string;
}

interface SpecSearchResult {
  results?: Array<{
    score: number;
    domain: string;
    section: string;
    title: string;
    text: string;
    linkedFiles?: string[];
  }>;
  error?: string;
}

interface ImpactResult {
  symbol?: string;
  file?: string;
  riskScore?: number;
  riskLevel?: string;
  recommendedStrategy?: string;
  metrics?: { fanIn: number; fanOut: number; isHub: boolean };
  error?: string;
}

// ============================================================================
// PROPOSAL TEMPLATE BUILDER
// ============================================================================

function riskBadge(score: number): string {
  if (score <= 20) return '🟢 low';
  if (score <= 45) return '🟡 medium';
  if (score <= 70) return '🟠 high';
  return '🔴 critical';
}

function buildProposal(
  slug: string,
  description: string,
  storyContent: string | undefined,
  orient: OrientResult,
  specSearch: SpecSearchResult,
  impacts: ImpactResult[],
  generatedAt: string,
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Proposal: ${slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}`);
  lines.push('');
  lines.push(`> Generated by spec-gen on ${generatedAt}`);
  lines.push(`> Source: ${storyContent ? 'BMAD story' : 'intent description'}`);
  lines.push(`> Status: draft`);
  lines.push('');

  // Intent
  lines.push('## Intent');
  lines.push('');
  lines.push(description);
  lines.push('');

  if (storyContent) {
    lines.push('### Story');
    lines.push('');
    lines.push('```');
    lines.push(storyContent.trim());
    lines.push('```');
    lines.push('');
  }

  // Spec domains affected
  const domains = orient.specDomains ?? [];
  if (domains.length > 0) {
    lines.push('## Spec Domains Affected');
    lines.push('');
    lines.push('| Domain | Spec File | Match Count |');
    lines.push('|--------|-----------|-------------|');
    for (const d of domains) {
      lines.push(`| \`${d.domain}\` | \`${d.specFile}\` | ${d.matchCount} |`);
    }
    lines.push('');
  } else {
    lines.push('## Spec Domains Affected');
    lines.push('');
    lines.push('> No spec domains found. Run `spec-gen generate` to create specs from this codebase.');
    lines.push('');
  }

  // Existing requirements touched
  const specResults = specSearch.results ?? [];
  if (specResults.length > 0) {
    lines.push('## Existing Requirements Touched');
    lines.push('');
    lines.push('> Review these before writing new requirements — avoid duplication.');
    lines.push('');

    const byDomain = new Map<string, typeof specResults>();
    for (const r of specResults) {
      const bucket = byDomain.get(r.domain) ?? [];
      bucket.push(r);
      byDomain.set(r.domain, bucket);
    }

    for (const [domain, reqs] of byDomain) {
      lines.push(`### Domain: \`${domain}\``);
      lines.push('');
      for (const req of reqs) {
        const scoreStr = req.score.toFixed(2);
        lines.push(`**${req.title}** *(relevance: ${scoreStr})*`);
        if (req.section) lines.push(`*Section: ${req.section}*`);
        lines.push('');
        const preview = req.text.length > 400 ? req.text.slice(0, 400) + '…' : req.text;
        for (const line of preview.split('\n')) lines.push(`> ${line}`);
        if (req.linkedFiles && req.linkedFiles.length > 0) {
          lines.push('');
          lines.push(`*Linked files: ${req.linkedFiles.map(f => `\`${f}\``).join(', ')}*`);
        }
        lines.push('');
      }
    }
  }

  // Proposed spec changes (scaffold for human completion)
  lines.push('## Proposed Spec Changes');
  lines.push('');
  lines.push('> Complete this section. Then run `openspec specs ' + slug + '` to formalise.');
  lines.push('');

  if (domains.length > 0) {
    for (const d of domains.slice(0, 3)) {
      lines.push(`### Domain: \`${d.domain}\``);
      lines.push('');
      lines.push('- [ ] **Add requirement**: <!-- describe new behaviour in RFC 2119 (SHALL/SHOULD/MAY) -->');
      lines.push('- [ ] **Modify requirement**: <!-- existing requirement id + what changes -->');
      lines.push('- [ ] **Add scenario**: <!-- Given / When / Then -->');
      lines.push('');
    }
  } else {
    lines.push('- [ ] **Add requirement**: <!-- describe new behaviour in RFC 2119 (SHALL/SHOULD/MAY) -->');
    lines.push('- [ ] **Add scenario**: <!-- Given / When / Then -->');
    lines.push('');
  }

  // Technical context
  lines.push('## Technical Context');
  lines.push('');
  lines.push('> Generated by spec-gen static analysis. Do not edit this section manually.');
  lines.push('');

  // Affected functions
  const topFunctions = (orient.relevantFunctions ?? []).slice(0, 5);
  if (topFunctions.length > 0) {
    lines.push('### Affected Functions');
    lines.push('');
    lines.push('| Function | File | Fan-in | Fan-out | Hub |');
    lines.push('|----------|------|--------|---------|-----|');
    for (const fn of topFunctions) {
      const hub = fn.isHub ? '⚠️ yes' : 'no';
      lines.push(`| \`${fn.name}\` | \`${fn.filePath}\` | ${fn.fanIn} | ${fn.fanOut} | ${hub} |`);
    }
    lines.push('');
  }

  // Risk assessment
  const validImpacts = impacts.filter(i => i.riskScore !== undefined);
  if (validImpacts.length > 0) {
    lines.push('### Risk Assessment');
    lines.push('');
    lines.push('| Function | Risk Score | Level | Strategy |');
    lines.push('|----------|-----------|-------|----------|');
    for (const i of validImpacts) {
      const score = i.riskScore ?? 0;
      lines.push(
        `| \`${i.symbol}\` | ${score} | ${riskBadge(score)} | \`${i.recommendedStrategy ?? 'n/a'}\` |`
      );
    }
    lines.push('');

    const maxRisk = Math.max(...validImpacts.map(i => i.riskScore ?? 0));
    if (maxRisk >= 70) {
      lines.push('> ⚠️ **High risk detected.** Run `bmad/tasks/brownfield-refactor.md` before implementing this change.');
      lines.push('');
    } else if (maxRisk >= 40) {
      lines.push('> ⚠️ **Moderate risk.** Ensure callers are covered by tests before implementing.');
      lines.push('');
    }
  }

  // Insertion points
  const insertionPoints = orient.insertionPoints ?? [];
  if (insertionPoints.length > 0) {
    lines.push('### Insertion Points');
    lines.push('');
    for (const ip of insertionPoints) {
      lines.push(`${ip.rank}. **\`${ip.name}\`** in \`${ip.filePath}\``);
      lines.push(`   - Role: \`${ip.role}\` | Strategy: \`${ip.strategy}\``);
      lines.push(`   - ${ip.reason}`);
    }
    lines.push('');
  }

  // Next steps
  lines.push('## Next Steps');
  lines.push('');
  lines.push(`- [ ] Complete "Proposed Spec Changes" above`);
  lines.push(`- [ ] \`openspec specs ${slug}\` — formalise spec delta`);
  lines.push(`- [ ] \`openspec design ${slug}\` — technical design`);
  lines.push(`- [ ] \`openspec tasks ${slug}\` — implementation task list`);
  if (validImpacts.some(i => (i.riskScore ?? 0) >= 70)) {
    lines.push(`- [ ] Run \`bmad/tasks/brownfield-refactor.md\` for high-risk functions before implementation`);
  }
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// HANDLER
// ============================================================================

export async function handleGenerateChangeProposal(
  directory: string,
  description: string,
  slug: string,
  storyContent?: string,
): Promise<unknown> {
  const absDir = await validateDirectory(directory);

  // Normalise slug: lowercase, hyphens only
  const safeSlug = slug
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!safeSlug) {
    return { error: 'Invalid slug. Use alphanumeric characters and hyphens, e.g. "add-payment-retry".' };
  }

  const changeDir = join(absDir, 'openspec', 'changes', safeSlug);
  const proposalPath = join(changeDir, 'proposal.md');

  const generatedAt = new Date().toISOString().split('T')[0];

  // ── Parallel orientation + spec search ────────────────────────────────────
  const [orientRaw, specSearchRaw] = await Promise.all([
    handleOrient(directory, description, 7),
    handleSearchSpecs(directory, description, 5),
  ]);

  const orient = orientRaw as OrientResult;
  const specSearch = specSearchRaw as SpecSearchResult;

  // ── Impact analysis on top 2 functions (best-effort) ──────────────────────
  const topFunctions = (orient.relevantFunctions ?? []).slice(0, 2);
  const impacts: ImpactResult[] = [];

  for (const fn of topFunctions) {
    try {
      const raw = await handleAnalyzeImpact(directory, fn.name, 2);
      const impact = raw as ImpactResult;
      if (!impact.error) impacts.push(impact);
    } catch {
      // non-fatal — proceed with partial context
    }
  }

  // ── Build proposal ─────────────────────────────────────────────────────────
  const content = buildProposal(
    safeSlug,
    description,
    storyContent,
    orient,
    specSearch,
    impacts,
    generatedAt,
  );

  // ── Write to disk ──────────────────────────────────────────────────────────
  await mkdir(changeDir, { recursive: true });
  await writeFile(proposalPath, content, 'utf8');

  // ── Summary ────────────────────────────────────────────────────────────────
  const domains = (orient.specDomains ?? []).map(d => d.domain);
  const maxRisk = impacts.length > 0
    ? Math.max(...impacts.map(i => i.riskScore ?? 0))
    : null;

  return {
    slug: safeSlug,
    proposalPath: join('openspec', 'changes', safeSlug, 'proposal.md'),
    domainsAffected: domains,
    functionsFound: (orient.relevantFunctions ?? []).length,
    requirementsTouched: (specSearch.results ?? []).length,
    maxRiskScore: maxRisk,
    riskLevel: maxRisk !== null
      ? (maxRisk <= 20 ? 'low' : maxRisk <= 45 ? 'medium' : maxRisk <= 70 ? 'high' : 'critical')
      : 'unknown',
    nextStep: `Review and complete openspec/changes/${safeSlug}/proposal.md, then run: openspec specs ${safeSlug}`,
    orientErrors: orient.error ? [orient.error] : [],
    specSearchErrors: specSearch.error ? [specSearch.error] : [],
  };
}
